### ISSUE TITLE
Typo on label

### ISSUE THREAD

**Issue by blackdragon1** [ka215/cdbt#5]
Hello, I noticed a typo in case you wanna get it fixed.
Inside Setting/Enable tables list, there is one column with the label "Choise Current table", Choise isn't a word it can be Choose (verb) or Chose (past tense) or Choice (a noun). In this case I would go it "Choose Current table", or just go with the buttons "Set Current table".

**Comment by ka215** [comment]
Thanks:-)

There was a typo for I have been low ability of my English translation, sorry. I think my plugin have as same typos yet. If you've noticed them, please point out them.

I will release soon a typo modified version.
